ALTER TABLE DimAccount
ADD CONSTRAINT fk_dimaccount_brokerid
FOREIGN KEY (SK_BrokerID) 
REFERENCES DimBroker (SK_BrokerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimAccount
ADD CONSTRAINT fk_dimaccount_customerid
FOREIGN KEY (SK_CustomerID) 
REFERENCES DimCustomer (SK_CustomerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimSecurity
ADD CONSTRAINT fk_dimsecurity_companyid
FOREIGN KEY (SK_CompanyID) 
REFERENCES DimCompany (SK_CompanyID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_brokerid
FOREIGN KEY (SK_BrokerID) 
REFERENCES DimBroker (SK_BrokerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_createdateid
FOREIGN KEY (SK_CreateDateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_createtimeid
FOREIGN KEY (SK_CreateTimeID) 
REFERENCES DimTime (SK_TimeID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_closedateid
FOREIGN KEY (SK_CloseDateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_closetimeid
FOREIGN KEY (SK_CloseTimeID) 
REFERENCES DimTime (SK_TimeID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_securityid
FOREIGN KEY (SK_SecurityID) 
REFERENCES DimSecurity (SK_SecurityID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_companyid
FOREIGN KEY (SK_CompanyID) 
REFERENCES DimCompany (SK_CompanyID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_customerid
FOREIGN KEY (SK_CustomerID) 
REFERENCES DimCustomer (SK_CustomerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE DimTrade
ADD CONSTRAINT fk_dimtrade_accountid
FOREIGN KEY (SK_AccountID) 
REFERENCES DimAccount (SK_AccountID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactCashBalances
ADD CONSTRAINT fk_factcashbalances_customerid
FOREIGN KEY (SK_CustomerID) 
REFERENCES DimCustomer (SK_CustomerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactCashBalances
ADD CONSTRAINT fk_factcashbalances_accountid
FOREIGN KEY (SK_AccountID) 
REFERENCES DimAccount (SK_AccountID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactCashBalances
ADD CONSTRAINT fk_factcashbalances_dateid
FOREIGN KEY (SK_DateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

-- ALTER TABLE FactCashBalances
-- ADD CONSTRAINT fk_factcashbalances_timeid
-- FOREIGN KEY (SK_TimeID) 
-- REFERENCES DimTime (SK_TimeID)
-- ON UPDATE CASCADE ON DELETE RESTRICT;

-- ALTER TABLE FactHoldings
-- ADD CONSTRAINT fk_factholdings_tradeid
-- FOREIGN KEY (SK_TradeID) 
-- REFERENCES DimTrade (SK_TradeID)
-- ON UPDATE CASCADE ON DELETE RESTRICT;

-- ALTER TABLE FactHoldings
-- ADD CONSTRAINT fk_factholdings_currenttradeid
-- FOREIGN KEY (SK_CurrentTradeID) 
-- REFERENCES DimTrade (SK_CurrentTradeID)
-- ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_customerid
FOREIGN KEY (SK_CustomerID) 
REFERENCES DimCustomer (SK_CustomerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_accountid
FOREIGN KEY (SK_AccountID) 
REFERENCES DimAccount (SK_AccountID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_securityid
FOREIGN KEY (SK_SecurityID) 
REFERENCES DimSecurity (SK_SecurityID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_companyid
FOREIGN KEY (SK_CompanyID) 
REFERENCES DimCompany (SK_CompanyID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_dateid
FOREIGN KEY (SK_DateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactHoldings
ADD CONSTRAINT fk_factholdings_timeid
FOREIGN KEY (SK_TimeID) 
REFERENCES DimTime (SK_TimeID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactMarketHistory
ADD CONSTRAINT fk_factmarkethistory_securityid
FOREIGN KEY (SK_SecurityID) 
REFERENCES DimSecurity (SK_SecurityID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactMarketHistory
ADD CONSTRAINT fk_factmarkethistory_companyid
FOREIGN KEY (SK_CompanyID) 
REFERENCES DimCompany (SK_CompanyID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactMarketHistory
ADD CONSTRAINT fk_factmarkethistory_dateid
FOREIGN KEY (SK_DateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactWatches
ADD CONSTRAINT fk_factwatches_customerid
FOREIGN KEY (SK_CustomerID) 
REFERENCES DimCustomer (SK_CustomerID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactWatches
ADD CONSTRAINT fk_factwatches_securityid
FOREIGN KEY (SK_SecurityID) 
REFERENCES DimSecurity (SK_SecurityID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactWatches
ADD CONSTRAINT fk_factwatches_dateid_dateplaced
FOREIGN KEY (SK_DateID_DatePlaced) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE FactWatches
ADD CONSTRAINT fk_factwatches_dateid_dateremoved
FOREIGN KEY (SK_DateID_DateRemoved) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE Prospect
ADD CONSTRAINT fk_prospect_updatedateid
FOREIGN KEY (SK_UpdateDateID) 
REFERENCES DimDate (SK_DateID)
ON UPDATE CASCADE ON DELETE RESTRICT;
